/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculator.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
arith_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		intWrapper sqr_1_arg;
		intPair add_1_arg;
		intTripple mul_1_arg;
		mystring disp_1_arg;
		intMinus diff_1_arg;
		intDivision div_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case SQR:
		_xdr_argument = (xdrproc_t) xdr_intWrapper;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) sqr_1_svc;
		break;

	case ADD:
		_xdr_argument = (xdrproc_t) xdr_intPair;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) add_1_svc;
		break;

	case MUL:
		_xdr_argument = (xdrproc_t) xdr_intTripple;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) mul_1_svc;
		break;

	case DISP:
		_xdr_argument = (xdrproc_t) xdr_mystring;
		_xdr_result = (xdrproc_t) xdr_mystring;
		local = (char *(*)(char *, struct svc_req *)) disp_1_svc;
		break;

	case DIFF:
		_xdr_argument = (xdrproc_t) xdr_intMinus;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) diff_1_svc;
		break;

	case DIV:
		_xdr_argument = (xdrproc_t) xdr_intDivision;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) div_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (ARITH_PROG, ARITH_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, ARITH_PROG, ARITH_VERS, arith_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (ARITH_PROG, ARITH_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, ARITH_PROG, ARITH_VERS, arith_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (ARITH_PROG, ARITH_VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
